name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-back:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn clean verify
        working-directory: back

  build-front:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: front
        run: yarn install

      - name: Run tests with coverage
        working-directory: front
        run: |
          # Nettoyage et création du dossier coverage
          rm -rf coverage
          
          # Exécution unique des tests avec coverage
          yarn test --code-coverage --browsers=ChromeHeadlessCI --watch=false
          
          # Vérification et copie du rapport
          if [ -f "coverage/lcov.info" ]; then
            echo "✔ Rapport lcov.info trouvé et copié"
            cp coverage/lcov.info ../front-coverage.info
          else
            echo "::error::Fichier lcov.info introuvable dans coverage/"
            echo "Contenu du dossier coverage:"
            ls -la coverage/
            exit 1
          fi

      - name: Verify coverage report
        run: |
          echo "=== Vérification finale ==="
          echo "Taille du rapport: $(wc -l < front-coverage.info) lignes"
          echo "Extrait du rapport:"
          head -5 front-coverage.info

  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [build-back, build-front]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: SonarCloud Scan
        working-directory: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Vérification ultime du rapport
          ls -la ../front-coverage.info
          echo "Premières lignes:"
          head -5 ../front-coverage.info
          
          # Analyse Sonar avec paramètres optimisés
          mvn verify sonar:sonar \
            -Dsonar.projectKey=Shishifoxy_bobapp-ci-cd \
            -Dsonar.organization=shishifoxy \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.javascript.lcov.reportPaths=../front-coverage.info \
            -Dsonar.typescript.lcov.reportPaths=../front-coverage.info \
            -Dsonar.sources=src,../front/src \
            -Dsonar.tests=src/test,../front/src/app \
            -Dsonar.sourceEncoding=UTF-8

  docker-publish:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: sonar-analysis
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: |
          docker build -t shishifoxy1/bobapp-back ./back
          docker push shishifoxy1/bobapp-back
      - run: |
          docker build -t shishifoxy1/bobapp-front ./front
          docker push shishifoxy1/bobapp-front

  deploy:
    name: Simulated Deploy
    runs-on: ubuntu-latest
    needs: [docker-publish]
    steps:
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - run: |
          docker pull shishifoxy1/bobapp-back:latest
          docker pull shishifoxy1/bobapp-front:latest
          docker network create bobapp-network
          docker run -d --name bobapp-back --network bobapp-network -p 8080:8080 shishifoxy1/bobapp-back:latest
          docker run -d --name bobapp-front --network bobapp-network -p 8081:80 shishifoxy1/bobapp-front:latest